version: "3.6"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile.dev
    depends_on:
      - mysql
      - redis
#      - elasticsearch
    environment:
      DATABASE_HOSTNAME: mysql
      DATABASE_PORT: 3306
      REDIS_HOSTNAME: redis
    volumes:
      - .:/app
    working_dir: /app
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: vapor
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: vapor-test
    logging:
      driver: none
  redis:
    image: redis:alpine
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
#    environment:
#      cluster.name: es-docker-cluster
#      node.name: es-docker-node
#      node.master: true
#      node.data: true
#      node.ml: false
#      network.host: 0.0.0.0
#      xpack.monitoring.enabled: false
#      xpack.security.enabled: false
#      xpack.ml.enabled: false
#      xpack.watcher.enabled: false
#      bootstrap.memory_lock: true
#      ES_JAVA_OPTS: -Xms512m -Xmx512m
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: 1g
#    volumes:
#     # If you want to use a custom configuration file, simply uncomment
#     # the below and place a file named elasticsearch.yml in this directory.
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
